### ISSUE TITLE
PSoC 4 support

### ISSUE THREAD

**Issue by Stredoslovak** [RolfNoot/PSoC5_VS_Code#1]
Hello, stumbled across your project just today in the Infineton forum post you've made. You are advertising PSoC4 support as well, yet I can't seem to find it here on GitHub, or should I just use the PSoC5_VS_Code repo?

Thanks.

**Comment by RolfNoot** [comment]
Hi,

I just added a PSoC4 project / template. Please see: https://github.com/RolfNoot/PSoC4_VS_Code

**Comment by Stredoslovak** [comment]
Great
Thanks, will look into it.
